services:
  - type: web
    name: restaurant-backend
    runtime: java
    plan: free

    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: JWT_SECRET
        value: restaurant-management-system-secret-key-2026-change-me-very-long

      - key: SPRING_DATASOURCE_URL
        sync: false

      - key: SPRING_DATASOURCE_USERNAME
        sync: false

      - key: SPRING_DATASOURCE_PASSWORD
        sync: false